insert into users (name_user, passwrd, programa, tipo, username) VALUES ('Sebastian Piñeros', '12345', 'Sistemas', 'Estudiante', 'jhon.pineros');
insert into users (name_user, passwrd, programa, tipo, username) VALUES ('Juan baez', 'baez', 'Sistemas', 'Estudiante', 'juan.baez');
insert into users (name_user, passwrd, programa, tipo, username) VALUES ('Nicolas Palacios', 'pala', 'Sistemas', 'Estudiante', 'nicolas.palacios');
insert into users (name_user, passwrd, programa, tipo, username) VALUES ('admin', 'admin', NULL, 'Administrador', 'admin');

insert into schedules (nombre) VALUES ('schedule 1');
insert into schedules (nombre) VALUES ('schedule 2');
insert into schedules (nombre) VALUES ('schedule 3');

insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (1, 'ARSW', 'Arquitectura de sofware', 'Andres Trivino');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (2, 'ARSW', 'Arquitectura de sofware', 'Andres Trivino');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (1, 'MMIN', 'Modelos matematicos para informatica', 'Wilmer Garzon');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (2, 'MMIN', 'Modelos matematicos para informatica', 'Juan Cortes');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (3, 'MMIN', 'Modelos matematicos para informatica', 'Raul Chaparro');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (1, 'AREP', 'Arquitecturas empresariales', 'Daniel Benavides');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (2, 'AREP', 'Arquitecturas empresariales', 'Daniel Benavides');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (1, 'IETI', 'Innovacion y emprendimiento con TI', 'Diego Jara');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (1, 'AYED', 'Algoritmos y estructuras de datos', 'Sebastian Martinez');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (2, 'AYED', 'Algoritmos y estructuras de datos', 'Sebastian Martinez');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (1, 'TPRO', 'Teoria de la programacion', 'Raul Chaparro');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (2, 'TPRO', 'Teoria de la programacion', 'Raul Chaparro');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (1, 'POOB', 'Programacion orientada a objetos', 'Rodrigo Gualtero');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (2, 'POOB', 'Programacion orientada a objetos', 'Laura Herrera');
insert into subjects (group_sub, memo_sub, name_sub, professor) VALUES (1, 'CVDS', 'Ciclos de vida del desarrollo de software', 'Julian Velasco');

insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('M', '8:30', '7:00', 1);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('J', '10:00', '7:00', 1);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('L', '8:30', '7:00', 2);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('X', '10:00', '7:00', 2);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('L', '14:30', '13:00', 3);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('J', '14:30', '13:00', 3);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('V', '14:30', '13:00', 3);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('M', '8:30', '7:00', 4);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('X', '11:30', '10:00', 4);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('V', '11:30', '10:00', 4);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('L', '14:30', '13:00', 5);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('J', '13:00', '11:30', 5);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('V', '14:30', '13:00', 5);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('J', '14:30', '13:00', 6);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('V', '14:30', '11:30', 6);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('J', '13:00', '11:30', 7);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('V', '17:30', '14:30', 7);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('X', '8:30', '7:00', 8);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('J', '19:00', '16:00', 8);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('J', '17:30', '16:00', 9);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('V', '19:00', '16:00', 9);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('L', '17:30', '16:00', 10);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('M', '19:00', '16:00', 10);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('X', '17:30', '16:00', 11);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('V', '11:30', '10:00', 11);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('M', '8:30', '7:00', 12);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('V', '10:00', '8:30', 12);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('M', '13:00', '10:00', 13);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('V', '13:00', '10:00', 13);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('S', '13:00', '10:00', 14);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('V', '10:00', '7:00', 14);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('X', '8:30', '7:00', 15);
insert into dates_subject (dia, end_time, start_time, id_subject) VALUES ('S', '10:00', '7:00', 15);

insert into schedulexsubject (id_subject,id_schedule) VALUES (2,1);
insert into schedulexsubject (id_subject,id_schedule) VALUES (3,1);
insert into schedulexsubject (id_subject,id_schedule) VALUES (4,2);
insert into schedulexsubject (id_subject,id_schedule) VALUES (4,3);

insert into userxschedule (id_user,id_schedule) VALUES (1,1);
insert into userxschedule (id_user,id_schedule) VALUES (1,3);
insert into userxschedule (id_user,id_schedule) VALUES (3,2);
